### ISSUE TITLE
Create a Slurm plugin for gathering NCCL_DEBUG logs

### ISSUE THREAD

**Issue by rdjjke** [nebius/soperator#714]
The purpose if this plugin is to implicitly collect traces for NCCL for easier debugging, so no action from the user won't be required to collect such logs in case of failures.
We have to manage `NCCL_DEBUG` for log level, as well as `NCCL_DEBUG_FILE` for storing collected logs. As the size of the trace logs can be significant, some logration/cleaning has to be involved.

**Comment by dstaroff** [comment]
`NCCL_DEBUG_FILE` doesn't support providing multiple files for the output, while we want to be able to write logs into both dedicated log file, and `stdout`.
The solution here is to create named pipe and use `tee` to listen for this pipe, and to redirect to needed outputs. It is also required to check if user provided debug file, and concatenate it to the list of targets provided to `tee`

**Comment by dstaroff** [comment]
```console
$ mkfifo /tmp/nccl.pipe
$ tee ~/nccl.log < /tmp/nccl.pipe &
$ NCCL_DEBUG=TRACE NCCL_DEBUG_FILE=/tmp/nccl.pipe all_reduce_perf -b 512M -e 8G -f 2 -g 1
...
worker-0:2719294:2719294 [0] NCCL INFO Bootstrap : Using eth0:10.0.68.126<0>
worker-0:2719294:2719294 [0] NCCL INFO NET/Plugin: No plugin found (libnccl-net.so)
worker-0:2719294:2719294 [0] NCCL INFO NET/Plugin: Plugin load returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory : when loading libnccl-net.so
worker-0:2719294:2719294 [0] NCCL INFO NET/Plugin: Using internal network plugin.
worker-0:2719294:2719294 [0] NCCL INFO cudaDriverVersion 12040
NCCL version 2.21.5+cuda12.4
worker-0:2719294:2719294 [0] NCCL INFO NCCL version 2.21.5+cuda12.4
worker-0:2719294:2719306 [0] NCCL INFO NET/IB : No device found.
worker-0:2719294:2719306 [0] NCCL INFO NET/Socket : Using [0]eth0:10.0.68.126<0>
worker-0:2719294:2719306 [0] NCCL INFO Using non-device net plugin version 0
worker-0:2719294:2719306 [0] NCCL INFO Using network Socket
worker-0:2719294:2719306 [0] NCCL INFO ncclCommInitRank comm 0x558edf864420 rank 0 nranks 1 cudaDev 0 nvmlDev 0 busId f000 commId 0x3065f079908b5247 - Init START
worker-0:2719294:2719306 [0] NCCL INFO comm 0x558edf864420 rank 0 nRanks 1 nNodes 1 localRanks 1 localRank 0 MNNVL 0
...
$ head nccl.log
worker-0:2719294:2719294 [0] NCCL INFO Bootstrap : Using eth0:10.0.68.126<0>
worker-0:2719294:2719294 [0] NCCL INFO NET/Plugin: No plugin found (libnccl-net.so)
worker-0:2719294:2719294 [0] NCCL INFO NET/Plugin: Plugin load returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory : when loading libnccl-net.so
worker-0:2719294:2719294 [0] NCCL INFO NET/Plugin: Using internal network plugin.
worker-0:2719294:2719294 [0] NCCL INFO cudaDriverVersion 12040
worker-0:2719294:2719294 [0] NCCL INFO NCCL version 2.21.5+cuda12.4
worker-0:2719294:2719306 [0] NCCL INFO NET/IB : No device found.
worker-0:2719294:2719306 [0] NCCL INFO NET/Socket : Using [0]eth0:10.0.68.126<0>
worker-0:2719294:2719306 [0] NCCL INFO Using non-device net plugin version 0
worker-0:2719294:2719306 [0] NCCL INFO Using network Socket
$ echo '' > nccl.log && NCCL_DEBUG=ERROR NCCL_DEBUG_FILE=/tmp/nccl.pipe all_reduce_perf -b 512M -e 8G -f 2 -g 1
# nThread 1 nGpus 1 minBytes 536870912 maxBytes 8589934592 step: 2(factor) warmup iters: 5 iters: 20 agg iters: 1 validation: 1 graph: 0
#
# Using devices
#  Rank  0 Group  0 Pid 2723462 on   worker-0 device  0 [0x0f] NVIDIA H100 80GB HBM3
...
$ cat nccl.log

$ 
```

**Comment by dstaroff** [comment]
The planned implementation here is as following:

# Args

- `level <LEVEL>` - forced log level. One of `Info|Error|Warn` etc.
- `[outfile <PATH>]` - path to the output file with support for basic Slurm formatting placeholders (e.g. `%j`). Could be omitted to disable writing to the file
- `[outstdout]` - whether to write debug logs to stdout
- `[pipefile <PATH>]` - path to the named pipe. Should support placeholders as well. By default, `/tmp/nccl.pipe`

# Implementation

`level` arg overwrites `NCCL_DEBUG` env var with provided value.

## Multiple targets

### No `outfile` and `outstdout` provided

Just set `NCCL_DEBUG`.

### Just `outfile` is provided

Set `NCCL_DEBUG_FILE`.

### `outstdout` is provided

In `slurm_spank_init`, named pipe has to be created to be set as `NCCL_DEBUG_FILE`.
In order to send its content to stdout, separate process with `tee` listening from the pipe has to be run.

### `NCCL_DEBUG_FILE` set in env by user

1. Combine list of ours and user's `NCCL_DEBUG_FILE`
2. Make it contain only unique values
3. Use the same approach with `tee` to write to multiple targets

if `outstdout` is not provided - redirect output of `tee` to `/dev/null`.

### Finalizing

If named pipe and `tee` were used, they have to be closed on `slurm_spank_exit`.

# Context

The most suitable context for the plugin is [`remote`](https://slurm.schedmd.com/spank.html#SECTION_SPANK-PLUGINS), I suppose.

# Considerations

## Pipe exclusiveness

Since multiple jobs could be running on the same node, all actions must be atomic and have no collisions.
In order to achieve this, named pipes have to have different pathes.

The most right way would be to use jobid inside the name. But it could be not used by the user. Implicitly inserting it to the pipe name is a breaking of a contract. So, the solution here could be to use mutex / lock file.

The `tee` process should be forked from the current process, and PID has to be saved.
On the exit stage, child process has to be killed.

To manage multiple jobs running on the same node, some struct could be implemented to contain info on `tee`'s PID and lock file path, primary key is job id.
This struct instances could be saved in vector/hashmap.

> It's worth checking if saved instances persist between `slurm_spank_init` and `slurm_spank_exit`.

## Log rotation

In order to eliminate possible run out of space, additional `maxlogsize` flag could be incorporated to control the size of the log file.
It has only apply to the log file created by the plugin, not the possible file provided by user via env.

In case of all factors being true:
- the flag is provided
- the file on such path exists
- the size limit is reached

the file has to be cleaned before opening the pipe.

**Comment by dstaroff** [comment]
We decided to:
- Give user an ability to enable or disable the plugin if it's already present in the plugstack.
- Keep the metadata (aka state) for each step in particular file. As well as for pipe for ensuring its exclisiveness.
- In order keep a logic simple, we won't provide an opportunity to set format of outfile and pipefile names to the user. Instead, we will give them an opportunity to provide a path where all data (state, log, fifo) will be stored.
- Use 4 layers of configuration:
  - 1. Plugin defaults defined in source code.
  - 2. Plugin arguments defined in `plugstack.conf` overriding all above.
  - 3. Env variables overriding all above.
  - 4. Srun options overriding all above.

So, the changes in design are as following:

## Args

- `[enabled]` - whether the plugin is active.
- `[log-level <LEVEL>]` - forced log level. One of `Info`|`Error`|`Warn` etc.
- `[out-dir <PATH>]` - path to the directory where all data will be stored.
- `[out-file] - whether to write debug logs to the out file.
- `[out-stdout]` - whether to write debug logs to stdout.

## Multiple targets

### No `out-file` and `out-stdout` provided

Just set `NCCL_DEBUG`.

### Just `out-file` is provided

Set `NCCL_DEBUG_FILE`.

### `out-stdout` is provided

Named pipe has to be created to be set as `NCCL_DEBUG_FILE`.
In order to send its content to stdout, separate process with `tee` listening from the pipe has to be run.

### `NCCL_DEBUG_FILE` set in env by user

Combine ours and user's `NCCL_DEBUG_FILE` into a list, and make it contain unique values only.

The same approach with `tee` is applied.
if `out-stdout` is not provided - redirect output of `tee` to `/dev/null`.

### Finalizing
If named pipe and `tee` were used, they have to be closed.

**Comment by dstaroff** [comment]
Also, log rotation is decided to be postponed.

**Comment by dstaroff** [comment]
We could also try writing mount configuration from the plugin, not from the hook, at the `ENROOT_MOUNTS` location, which would give us possibility to mount out directory from the plugin as well without complex logic and additional layers of FIFO/tee.

---

I've tested the idea and it didn't work out, because:
- In `slurm_spank_user_init` - there is no $ENROOT_MOUNTS defined in env
- In `slurm_spank_task_init[_privileged]` - we are already inside the container

The other way around is to create mount configuration within the plugin and to save it in `/etc/enroot/mounts.d`.

I've also tested it, and it works.

The reason is that Enroot builds `ENROOT_MOUNTS` on runtime, and it copies the mount configurations to the newly created file.
This way we will also be able to clean up the mount configuration once the job is done.
